password: '{cipher}bd3ad537c34b19ba86068ad638ec35552ccf3dff1853267b5b2aabb662714722'
server:
  port: 8081
spring:
  profiles:
    active: dev
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
  h2:
    console:
      enabled: true
